// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package auth

import (
	"database/sql"
	"github.com/go-playground/validator/v10"
	"github.com/oktapascal/go-simpro/app/permission"
	"github.com/oktapascal/go-simpro/app/user"
)

// Injectors from wire.go:

func Wire(validate *validator.Validate, db *sql.DB) *Router {
	repository := ProvideRepository()
	userRepository := user.ProvideRepository()
	permissionRepository := permission.ProvideRepository()
	service := ProvideService(repository, userRepository, permissionRepository, db)
	handler := ProvideHandler(service, validate)
	router := ProvideRoute(handler)
	return router
}
