// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package navigation

// Injectors from wire.go:

func Wire() *Router {
	repository := ProvideRepository()
	service := ProvideService(repository)
	handler := ProvideHandler(service)
	router := ProvideRoute(handler)
	return router
}
